# -*- coding: utf-8 -*-
"""Decision Tree Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mfxy63rukGcUQIU2COgrINXM5wF2kFHw

importing the lib
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Importing dataset"""

ds = pd.read_csv('Position_Salaries.csv')
x = ds.iloc[:,1:-1].values
y = ds.iloc[:,-1].values

print(x)

print(y)



"""training the whol dataset on the DTR"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x,y)

"""Predicting the new result"""

regressor.predict([[6.5]])

"""Visualising the DTR for higher resolution"""

X_grid = np.arange(min(x), max(x), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(X_grid,regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (DTR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

